query RawResponseTypeDedupQuery @raw_response_type {
  node(id: "1") {
    ...RawResponseTypeDedupFragment @alias
  }
  viewer {
    actor {
      ...RawResponseTypeDedupFragment @alias
    }
  }
}

fragment RawResponseTypeDedupFragment on User {
  id
  nameRenderer @match {
    ...PlainUserNameRenderer_name @module(name: "PlainUserNameRenderer.react")
    ...MarkdownUserNameRenderer_name
      @module(name: "MarkdownUserNameRenderer.react")
  }
}

fragment PlainUserNameRenderer_name on PlainUserNameRenderer {
  plaintext
}

fragment MarkdownUserNameRenderer_name on MarkdownUserNameRenderer {
  markdown
}
