#!/bin/bash
cd "$(dirname "$0")"
JASMINE=node_modules/jasmine-node/bin/jasmine-node
if [ ! -x $JASMINE ] || [ ! -f $JASMINE ]; then
  echo 'Jasmine is not installed. Run "npm install jasmine-node" from the "generator" directory' >&2
  exit 1
else
  CURRENT_DIR=`pwd`
  NODE_PATHS="$CURRENT_DIR/src:$CURRENT_DIR/src/__tests__"
  if [ -n "$NODE_PATH" ]; then
    NODE_PATHS="$NODE_PATH:$NODE_PATHS"
  fi
  export NODE_PATH=$NODE_PATHS
  echo 'Running core tests'
  $JASMINE --captureExceptions --matchall src/__tests__/
fi
