import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import relay from 'vite-plugin-relay';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    // This plugin enables Relay's Babel transform which
    // replaces each `graphql` tagged template literal with
    // the corresponding runtime artifact generated by the Relay compiler.
    relay,
  ],
});
