/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * @flow
 * @providesModule writeFlowFile
 */

'use strict';

const SignedSource = require('signedsource');

const printFlowTypes = require('printFlowTypes');

import type CodegenDirectory from 'CodegenDirectory';
import type {Fragment} from 'RelayIR';

function writeFlowFile(
  outputDirectory: CodegenDirectory,
  node: Fragment,
  buildCommand: string,
  platform?: ?string,
): void {
  const moduleName = node.name + '.flow';
  const header = `/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   ${buildCommand}
 *
 * ${'@'}providesModule ${moduleName}
 * ${SignedSource.getSigningToken()}
 * ${'@'}flow
 */

'use strict';

`;
  const types = printFlowTypes(node);

  if (!types) {
    throw new Error('No types generated for node: ' + node.name);
  }

  const fileName = platform ? moduleName + '.' + platform : moduleName;
  outputDirectory.writeFile(
    fileName + '.js',
    SignedSource.signFile(header + types + '\n')
  );
}

module.exports = writeFlowFile;
