/**
 * Copyright (c) 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @providesModule writeFlowFile
 * @flow
 */

'use strict';

const SignedSource = require('signedsource');

const printFlowTypes = require('printFlowTypes');

import type CodegenDirectory from 'CodegenDirectory';
import type {Fragment} from 'RelayIR';

function writeFlowFile(
  outputDirectory: CodegenDirectory,
  node: Fragment,
  buildCommand: string,
  platform?: ?string,
): void {
  const moduleName = node.name + '.flow';
  const header = `/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   ${buildCommand}
 *
 * ${'@'}providesModule ${moduleName}
 * ${SignedSource.getSigningToken()}
 * ${'@'}flow
 */

'use strict';

`;
  const types = printFlowTypes(node);

  if (!types) {
    throw new Error('No types generated for node: ' + node.name);
  }

  const fileName = platform ? moduleName + '.' + platform : moduleName;
  outputDirectory.writeFile(
    fileName + '.js',
    SignedSource.signFile(header + types + '\n')
  );
}

module.exports = writeFlowFile;
