// @generated SignedSource<<e817b7ff4ea00de7a744ac87f2b48f76>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/relay-codegen/tests/react_flight_codegen

mod react_flight_codegen;

use react_flight_codegen::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn flight_props() {
    let input = include_str!("react_flight_codegen/fixtures/flight-props.graphql");
    let expected = include_str!("react_flight_codegen/fixtures/flight-props.expected");
    test_fixture(transform_fixture, "flight-props.graphql", "react_flight_codegen/fixtures/flight-props.expected", input, expected);
}
