// @generated SignedSource<<6c7492316ddf0d129ffa794bb3be5850>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/relay-codegen/tests/request_metadata

mod request_metadata;

use request_metadata::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn valid_documents() {
    let input = include_str!("request_metadata/fixtures/valid-documents.graphql");
    let expected = include_str!("request_metadata/fixtures/valid-documents.expected");
    test_fixture(transform_fixture, "valid-documents.graphql", "request_metadata/fixtures/valid-documents.expected", input, expected);
}
