# Get help on options with `rustfmt --help=config`
# Please keep these in alphabetical order.
edition = "2021"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
merge_derives = false
use_field_init_shorthand = true
version = "Two"
