#!/usr/bin/env node

var babel = require('babel-core');
var fs = require('fs');
var glob = require('glob');
var mkdirp = require('mkdirp');
var path = require('path');
var rimraf = require('rimraf');

var root = path.resolve(__dirname, '..');
var lib = path.join(root, 'lib');
var src = path.join(root, 'src');

// Blow away prior build artifacts.
rimraf.sync(lib);

// Get the files to transform
var files = glob.sync('**/*.js', {
  cwd: src,
  ignore: '**/__tests__/*'}
);
files.forEach((file) => {
  // Make sure file is fully resolved
  var srcFile = path.resolve(src, file);
  var libFile = path.resolve(lib, file);

  // Make sure the full path the destination file exists so we can write to it
  mkdirp.sync(path.dirname(libFile));
  var code = babel.transformFileSync(srcFile).code;

  // Prepend @generated annotation
  code = '// @generated\n' + code;
  fs.writeFile(libFile, code, 'utf8');
});
