#!/bin/bash

ROOT_DIR=$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)

cd $ROOT_DIR
rm -r lib
babel src --ignore __tests__,tools --out-dir lib
for file in $(find lib -name \*.js); do
  echo '// @''generated' > $file.generated
  cat $file >> $file.generated
  mv $file.generated $file
done
