// @generated SignedSource<<1b4dda69152d0e601213a07cc73dbf0d>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/fixture-tests/tests/uppercase

mod uppercase;

use uppercase::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn hello() {
    let input = include_str!("uppercase/fixtures/hello.txt");
    let expected = include_str!("uppercase/fixtures/hello.expected");
    test_fixture(transform_fixture, "hello.txt", "uppercase/fixtures/hello.expected", input, expected);
}

#[test]
fn world() {
    let input = include_str!("uppercase/fixtures/world.txt");
    let expected = include_str!("uppercase/fixtures/world.expected");
    test_fixture(transform_fixture, "world.txt", "uppercase/fixtures/world.expected", input, expected);
}
