parameters:
  - name: publishPackage
    default: false
    type: boolean

jobs:
- job:
  displayName: Build Javascript
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '2.1.x'
    - task: NodeTool@0
      inputs:
        versionSpec: "16.13.1"
      displayName: "Install Node.js 16.13.1"

    - task: npmAuthenticate@0
      displayName: NPM Authenticate
      inputs:
        workingFile: .npmrc

    - script: yarn --frozen-lockfile --ignore-scripts
      displayName: Install Node dependencies

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: relay-bin-linux-x64
        targetPath: "$(System.DefaultWorkingDirectory)/artifacts/linux-x64"
    
    # - task: DownloadPipelineArtifact@2
    #   inputs:
    #     artifact: relay-bin-linux-arm64
    #     targetPath: "$(System.DefaultWorkingDirectory)/artifacts/linux-arm64"

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: relay-bin-macos-x64
        targetPath: "$(System.DefaultWorkingDirectory)/artifacts/macos-x64"

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: relay-bin-macos-arm64
        targetPath: "$(System.DefaultWorkingDirectory)/artifacts/macos-arm64"

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: relay-bin-win-x64
        targetPath: "$(System.DefaultWorkingDirectory)/artifacts/win-x64"

    - script: |
        chmod +x linux-x64/relay
        chmod +x macos-x64/relay
        chmod +x macos-arm64/relay
      displayName: Mark binaries as executable
      workingDirectory: "$(System.DefaultWorkingDirectory)/artifacts"

    - ${{ if eq(parameters['publishPackage'], true) }}:
      - template: azure-devops-templates/steps/ESRP-CodeSigning-253-and-135020002.yml@SkypeSpaces-Infra
        parameters:
          workingDirectory: "$(System.DefaultWorkingDirectory)/artifacts"
          pattern: "*.exe"

    - script: yarn run gulp release

    - ${{ if eq(parameters['publishPackage'], true) }}:
      - template: /.azure-devops/steps/publish.yml@self

  # - script: npm run ci:precheck
  #   displayName: Run CI Pre-check

  # - script: npm version
  #   displayName: Get versions

  # - script: npm ci
  #   displayName: Install dependencies

  # - script: npm run bundlesize
  #   displayName: Build & Check bundle size
