jobs:
- template: /.azure-devops/steps/build-compiler-job.yml
  parameters:
    target: x86_64-unknown-linux-musl
    poolName: 1ES-Teams-Ubuntu-Latest-Compliant-1ESPT
    os: linux
    buildName: relay
    artifactName: relay-bin-linux-x64
    features: vendored
- template: /.azure-devops/steps/build-compiler-job.yml
  parameters:
    target: x86_64-pc-windows-msvc
    poolName: 1ES-Teams-Windows-Latest-Compliant-1ESPT
    os: windows
    buildName: relay.exe
    artifactName: relay-bin-win-x64
- template: /.azure-devops/steps/build-compiler-job.yml
  parameters:
    target: x86_64-apple-darwin
    poolName: Azure Pipelines
    buildName: relay
    os: macOS
    artifactName: relay-bin-macos-x64
    hostArchitecture: x86_64
- template: /.azure-devops/steps/build-compiler-job.yml
  parameters:
    target: aarch64-apple-darwin
    poolName: Azure Pipelines
    buildName: relay
    os: macOS
    artifactName: relay-bin-macos-arm64
    hostArchitecture: ARM64
