import { createServer } from "node:http";
import { createYoga } from "graphql-yoga";
import { getSchema } from "./schema.ts"; // Will be generated by Grats

/**
 * This example app uses [Grats](https://grats.capt.dev) to define a GraphQL
 * schema. Look for the `@gqlType` and `@gqlField` annotations in the docblocks
 * to see which types and fields are exposed in the schema.
 */

const yoga = createYoga({ schema: getSchema() });
const server = createServer(yoga);

server.listen(4000, () => {
  console.log("Running a GraphQL API server at http://localhost:4000/graphql");
});

