// @generated SignedSource<<f3eca0f4ebeca1f4e8553e8e974c133a>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/relay-transforms/tests/inline_data_fragment

mod inline_data_fragment;

use inline_data_fragment::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn recursive() {
    let input = include_str!("inline_data_fragment/fixtures/recursive.graphql");
    let expected = include_str!("inline_data_fragment/fixtures/recursive.expected");
    test_fixture(transform_fixture, "recursive.graphql", "inline_data_fragment/fixtures/recursive.expected", input, expected);
}

#[test]
fn variables_invalid() {
    let input = include_str!("inline_data_fragment/fixtures/variables.invalid.graphql");
    let expected = include_str!("inline_data_fragment/fixtures/variables.invalid.expected");
    test_fixture(transform_fixture, "variables.invalid.graphql", "inline_data_fragment/fixtures/variables.invalid.expected", input, expected);
}
