// @generated SignedSource<<e15c16944558d130c31c4e6db2160a1d>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/graphql-syntax/tests/print

mod print;

use print::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn schema() {
    let input = include_str!("print/fixtures/schema.graphql");
    let expected = include_str!("print/fixtures/schema.expected");
    test_fixture(transform_fixture, "schema.graphql", "print/fixtures/schema.expected", input, expected);
}
