name: Setup publishing environment
description: Installs JS dependencies, downloads all Relay compiler binary artifacts, and marks them as executable

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'
    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile --ignore-scripts
    - name: Download artifact relay-bin-linux-x64
      uses: actions/download-artifact@v7
      with:
        name: relay-bin-linux-x64
        path: artifacts/linux-x64
    - name: Download artifact relay-bin-linux-arm64
      uses: actions/download-artifact@v7
      with:
        name: relay-bin-linux-arm64
        path: artifacts/linux-arm64
    - name: Download artifact relay-bin-macos-x64
      uses: actions/download-artifact@v7
      with:
        name: relay-bin-macos-x64
        path: artifacts/macos-x64
    - name: Download artifact relay-bin-macos-arm64
      uses: actions/download-artifact@v7
      with:
        name: relay-bin-macos-arm64
        path: artifacts/macos-arm64
    - name: Download artifact relay-bin-win-x64
      uses: actions/download-artifact@v7
      with:
        name: relay-bin-win-x64
        path: artifacts/win-x64
    - name: Mark binaries as executable
      shell: bash
      working-directory: artifacts
      run: |
        chmod +x linux-x64/relay
        chmod +x linux-arm64/relay
        chmod +x macos-x64/relay
        chmod +x macos-arm64/relay
