// @generated SignedSource<<01752f0fa15f1e5e916c0c279ec6c71a>>
// Generated by $ cargo run -p fixture-tests -- oss/crates/schema-print/tests/print_schema

mod print_schema;

use print_schema::transform_fixture;
use fixture_tests::test_fixture;

#[test]
fn kitchen_sink() {
    let input = include_str!("print_schema/fixtures/kitchen-sink.graphql");
    let expected = include_str!("print_schema/fixtures/kitchen-sink.expected");
    test_fixture(transform_fixture, "kitchen-sink.graphql", "print_schema/fixtures/kitchen-sink.expected", input, expected);
}
