# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Compiler Explorer

on:
  push:
    branches:
      - main

jobs:
  build-compiler-explorer:
    if: false # disabling to unblock CI builds
    name: Build Compiler Explorer
    runs-on: macos-latest # wasm-pack not working on Ubuntu https://github.com/rustwasm/wasm-pack/issues/781
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          override: true
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: "Build Compiler Playground Wasm NPM package"
        run: wasm-pack build --target web
        working-directory: ./compiler/crates/relay-compiler-playground
      - uses: actions/upload-artifact@v3
        with:
          name: compiler-playground-package
          path: compiler/crates/relay-compiler-playground/pkg/
