# [registries]
# domorexp = { index = "sparse+https://domoreexp.pkgs.visualstudio.com/_packaging/npm-mirror/Cargo/index/" }
# [source.crates-io]
# replace-with = "domorexp"
# [unstable]
# registry-auth = true
